version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2
  cli: circleci/circleci-cli@volatile

commands:
  # based on the orb-tools/local-test-build
  test:
    parameters:
      test-file:
        type: string
      should-fail:
        description: If it's set to false, this job will fail if the local test job fails. If it's set to true, this job will fail if the local test job does not fail.
        type: boolean
        default: false
    steps:
      - run: cp << parameters.test-file >> tmp-config-src/config.yml
      - orb-tools/pack:
          source: tmp-config-src
          destination: uncompiled-config.yml
      - run: cat uncompiled-config.yml
      - run:
          name: compile test config
          command: circleci config process uncompiled-config.yml > config.yml
      - run:
          # Local env doesn't have all the env vars. So we explicitly define the necessary vars here.
          name: run the local test
          command: >
            <<# parameters.should-fail >>! <</ parameters.should-fail>>circleci local execute
            -e "INSPECODE_API_TOKEN=${INSPECODE_API_TOKEN}"
            -e "CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME}"
            -e "CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}"
            -e "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
            -e "CIRCLE_SHA1=${CIRCLE_SHA1}"
            --job inspecode/run
            -c config.yml | tee /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      # based on the config here: https://github.com/CircleCI-Public/hello-orb/blob/master/.circleci/config.yml
      # and https://github.com/sue445/circleci-ruby-orbs/blob/1.3.10/.circleci/config.yml
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/test-in-builds:
          name: test the valid setting
          orb-location: packed/orb.yml
          orb-name: inspecode
          test-steps:
            - test:
                test-file: test/valid.yml
          checkout: true
          attach-workspace: true
          requires:
            - orb-tools/pack

      - orb-tools/test-in-builds:
          name: test the setting with no api token
          orb-location: packed/orb.yml
          orb-name: inspecode
          test-steps:
            - test:
                test-file: test/no_api_token.yml
                should-fail: true
          checkout: true
          attach-workspace: true
          requires:
            - orb-tools/pack

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "rocro/inspecode@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "${CIRCLECI_API_TOKEN}"
          attach-workspace: true
          checkout: false
          requires:
            - orb-tools/test-in-builds
