version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2
  cli: circleci/circleci-cli@volatile

jobs:
  # based on the orb-tools/local-test-build
  test:
    parameters:
      test-file:
        type: string
      should-fail:
        description: If it's set to false, this job will fail if the local test job fails. If it's set to true, this job will fail if the local test job does not fail.
        type: boolean
        default: false
    # `circleci local execute` depends on the docker command
    machine: true
    steps:
      - cli/install
      - checkout
      - run:
          name: Set orb parameters to the values in the test file
          command: "echo -e \"orbs:\n  inspecode: rocro/inspecode@dev:${CIRCLE_BRANCH}\" >><<parameters.test-file>>"
      - run:
          # `circleci local execute` doesn't support v2.1 format. This is the workaround for this.
          name: Compile the test file
          command: circleci config process <<parameters.test-file>> > <<parameters.test-file>>.compiled
      - run:
          # Local env doesn't have all the env vars. So we explicitly define the necessary vars here.
          name: Run the local test
          command: >
            <<# parameters.should-fail >>! <</ parameters.should-fail>>circleci local execute
            -e "INSPECODE_API_TOKEN=${INSPECODE_API_TOKEN}"
            -e "CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME}"
            -e "CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}"
            -e "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
            -e "CIRCLE_SHA1=${CIRCLE_SHA1}"
            --job inspecode/run
            -c <<parameters.test-file>>.compiled | tee /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      # based on the config here: https://github.com/CircleCI-Public/hello-orb/blob/master/.circleci/config.yml
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "rocro/inspecode@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "${CIRCLECI_API_TOKEN}"
          attach-workspace: true
          checkout: false
          requires:
            - orb-tools/pack

      - test:
          test-file: test/valid.yml
          requires:
            - orb-tools/publish
          name: test the valid setting

      - test:
          test-file: test/no_api_token.yml
          should-fail: true
          requires:
            - orb-tools/publish
          name: test the setting with no api token
